import { JarPreset } from "./types";

export const JAR_PRESET_6: JarPreset[] = [
  {
    name: "Thiết yếu",
    slug: "essential",
    color: "#2563EB",
    icon: "house",
    jarType: "essential",
    monthlyStrategy: "percent",
    incomePercent: 55,
    spendPolicy: "flexible",
    sortOrder: 10,
  },
  {
    name: "Tự do tài chính",
    slug: "ffa",
    color: "#16A34A",
    icon: "trending-up",
    jarType: "investment",
    monthlyStrategy: "percent",
    incomePercent: 10,
    spendPolicy: "invest_only",
    sortOrder: 20,
  },
  {
    name: "Tiết kiệm dài hạn",
    slug: "lts",
    color: "#7C3AED",
    icon: "piggy-bank",
    jarType: "long_term_saving",
    monthlyStrategy: "percent",
    incomePercent: 10,
    spendPolicy: "long_term_only",
    sortOrder: 30,
  },
  {
    name: "Giáo dục",
    slug: "education",
    color: "#0EA5E9",
    icon: "book-open",
    jarType: "education",
    monthlyStrategy: "percent",
    incomePercent: 10,
    spendPolicy: "flexible",
    sortOrder: 40,
  },
  {
    name: "Hưởng thụ",
    slug: "play",
    color: "#F59E0B",
    icon: "party-popper",
    jarType: "play",
    monthlyStrategy: "percent",
    incomePercent: 10,
    spendPolicy: "must_spend",
    sortOrder: 50,
  },
  {
    name: "Cho đi",
    slug: "give",
    color: "#DC2626",
    icon: "heart-handshake",
    jarType: "give",
    monthlyStrategy: "percent",
    incomePercent: 5,
    spendPolicy: "give_only",
    sortOrder: 60,
  },
];
