import {
  AccountType,
  type AccountType as AccountTypeValue,
} from "./account-constants";

/** Stable persisted choices for ledger-owned accounts and categories. */
export const IconKey = {
  ACCOUNT: "account",
  BANK: "bank",
  WALLET: "wallet",
  CASH: "cash",
  BANKNOTE: "banknote",
  COINS: "coins",
  CREDIT_CARD: "credit-card",
  DEBIT_CARD: "debit-card",
  SAVINGS: "savings",
  SAVINGS_ACCOUNT: "savings-account",
  PIGGY_BANK: "piggy-bank",
  VAULT: "vault",
  SAFE: "safe",
  INVESTMENT: "investment",
  STOCK: "stock",
  FUND: "fund",
  BOND: "bond",
  PROVIDER_BANK: "provider-bank",
  PROVIDER_WALLET: "provider-wallet",
  PROVIDER_PHONE: "provider-phone",
  COFFEE: "coffee",
  FOOD: "food",
  RESTAURANT: "restaurant",
  GROCERIES: "groceries",
  DINING_OUT: "dining-out",
  SNACKS: "snacks",
  SHOPPING: "shopping",
  CLOTHING: "clothing",
  BEAUTY: "beauty",
  GIFT: "gift",
  CELEBRATION: "celebration",
  TRAVEL: "travel",
  FLIGHT: "flight",
  HOTEL: "hotel",
  TRANSPORT: "transport",
  FUEL: "fuel",
  PARKING: "parking",
  PUBLIC_TRANSIT: "public-transit",
  TAXI: "taxi",
  VEHICLE: "vehicle",
  HOME: "home",
  RENT: "rent",
  MORTGAGE: "mortgage",
  UTILITIES: "utilities",
  ELECTRICITY: "electricity",
  WATER: "water",
  INTERNET: "internet",
  PHONE: "phone",
  HOUSEHOLD_SUPPLIES: "household-supplies",
  REPAIRS: "repairs",
  FURNITURE: "furniture",
  HEALTH: "health",
  MEDICINE: "medicine",
  FITNESS: "fitness",
  EDUCATION: "education",
  BOOKS: "books",
  CHILDCARE: "childcare",
  PETS: "pets",
  ENTERTAINMENT: "entertainment",
  STREAMING: "streaming",
  GAMING: "gaming",
  FAMILY: "family",
  CHARITY: "charity",
  INSURANCE: "insurance",
  TAXES: "taxes",
  FEES: "fees",
  SALARY: "salary",
  FREELANCE: "freelance",
  BUSINESS_INCOME: "business-income",
  BONUS: "bonus",
  INVESTMENT_INCOME: "investment-income",
  SUBSCRIPTION: "subscription",
  WEDDING: "wedding",
  FUNERAL: "funeral",
  RELIGIOUS_GIVING: "religious-giving",
  PERSONAL_CARE: "personal-care",
  ELECTRONICS: "electronics",
  OFFICE: "office",
  CHILDCARE_SCHOOL: "childcare-school",
  VACATION: "vacation",
  HOBBY: "hobby",
  REFUND_CATEGORY: "refund-category",
  BANK_FEE: "bank-fee",
  OTHER: "other",
} as const;
export type IconKey = (typeof IconKey)[keyof typeof IconKey];

export const ACCOUNT_ICON_KEYS = [
  IconKey.ACCOUNT,
  IconKey.BANK,
  IconKey.WALLET,
  IconKey.CASH,
  IconKey.BANKNOTE,
  IconKey.COINS,
  IconKey.CREDIT_CARD,
  IconKey.DEBIT_CARD,
  IconKey.SAVINGS,
  IconKey.SAVINGS_ACCOUNT,
  IconKey.PIGGY_BANK,
  IconKey.VAULT,
  IconKey.SAFE,
  IconKey.INVESTMENT,
  IconKey.STOCK,
  IconKey.FUND,
  IconKey.BOND,
  IconKey.PROVIDER_BANK,
  IconKey.PROVIDER_WALLET,
  IconKey.PROVIDER_PHONE,
] as const;
export type AccountIconKey = (typeof ACCOUNT_ICON_KEYS)[number];

export const DEFAULT_ACCOUNT_ICON_KEY_BY_TYPE: Record<
  AccountTypeValue,
  AccountIconKey
> = {
  [AccountType.CASH]: IconKey.CASH,
  [AccountType.CHECKING]: IconKey.BANK,
  [AccountType.SAVINGS]: IconKey.SAVINGS_ACCOUNT,
  [AccountType.EWALLET]: IconKey.WALLET,
  [AccountType.BROKERAGE]: IconKey.INVESTMENT,
  [AccountType.CREDIT_CARD]: IconKey.CREDIT_CARD,
  [AccountType.SAVINGS_PRODUCT]: IconKey.SAVINGS,
  [AccountType.OTHER]: IconKey.ACCOUNT,
};

export const CATEGORY_ICON_KEYS = [
  IconKey.COFFEE,
  IconKey.FOOD,
  IconKey.RESTAURANT,
  IconKey.GROCERIES,
  IconKey.DINING_OUT,
  IconKey.SNACKS,
  IconKey.SHOPPING,
  IconKey.CLOTHING,
  IconKey.BEAUTY,
  IconKey.GIFT,
  IconKey.CELEBRATION,
  IconKey.TRAVEL,
  IconKey.FLIGHT,
  IconKey.HOTEL,
  IconKey.TRANSPORT,
  IconKey.FUEL,
  IconKey.PARKING,
  IconKey.PUBLIC_TRANSIT,
  IconKey.TAXI,
  IconKey.VEHICLE,
  IconKey.HOME,
  IconKey.RENT,
  IconKey.MORTGAGE,
  IconKey.UTILITIES,
  IconKey.ELECTRICITY,
  IconKey.WATER,
  IconKey.INTERNET,
  IconKey.PHONE,
  IconKey.HOUSEHOLD_SUPPLIES,
  IconKey.REPAIRS,
  IconKey.FURNITURE,
  IconKey.HEALTH,
  IconKey.MEDICINE,
  IconKey.FITNESS,
  IconKey.EDUCATION,
  IconKey.BOOKS,
  IconKey.CHILDCARE,
  IconKey.PETS,
  IconKey.ENTERTAINMENT,
  IconKey.STREAMING,
  IconKey.GAMING,
  IconKey.FAMILY,
  IconKey.CHARITY,
  IconKey.INSURANCE,
  IconKey.TAXES,
  IconKey.FEES,
  IconKey.SALARY,
  IconKey.FREELANCE,
  IconKey.BUSINESS_INCOME,
  IconKey.BONUS,
  IconKey.INVESTMENT_INCOME,
  IconKey.SUBSCRIPTION,
  IconKey.WEDDING,
  IconKey.FUNERAL,
  IconKey.RELIGIOUS_GIVING,
  IconKey.PERSONAL_CARE,
  IconKey.ELECTRONICS,
  IconKey.OFFICE,
  IconKey.CHILDCARE_SCHOOL,
  IconKey.VACATION,
  IconKey.HOBBY,
  IconKey.REFUND_CATEGORY,
  IconKey.BANK_FEE,
  IconKey.OTHER,
] as const;
export type CategoryIconKey = (typeof CATEGORY_ICON_KEYS)[number];

export const DEFAULT_CATEGORY_ICON_KEY: CategoryIconKey = IconKey.OTHER;

const ACCOUNT_ICON_KEY_SET = new Set<string>(ACCOUNT_ICON_KEYS);
const CATEGORY_ICON_KEY_SET = new Set<string>(CATEGORY_ICON_KEYS);

export function isAccountIconKey(value: string): value is AccountIconKey {
  return ACCOUNT_ICON_KEY_SET.has(value);
}

export function isCategoryIconKey(value: string): value is CategoryIconKey {
  return CATEGORY_ICON_KEY_SET.has(value);
}
