export const DEFAULT_ASSUMPTIONS = {
  INFLATION_ANNUAL: 0.04,
  CASH_RETURN_ANNUAL: 0.03,
  INVESTMENT_RETURN_ANNUAL: 0.10,
  PROPERTY_GROWTH_ANNUAL: 0.05,
  GOLD_GROWTH_ANNUAL: 0.04,
  SALARY_GROWTH_ANNUAL: 0.07,
} as const;

export const PERCENTAGE_MULTIPLIER = 100;
