import type { IconSvgElement } from "@hugeicons/react";
import {
  IconKey,
  type AccountIconKey,
  type CategoryIconKey,
} from "@/modules/ledger/application/icon-constants";
import {
  StitchAccountIcon,
  StitchBankIcon,
  StitchWalletIcon,
  StitchCashIcon,
  StitchBanknoteIcon,
  StitchCoinsIcon,
  StitchCreditCardIcon,
  StitchDebitCardIcon,
  StitchSavingsIcon,
  StitchSavingsAccountIcon,
  StitchPiggyBankIcon,
  StitchVaultIcon,
  StitchSafeIcon,
  StitchInvestmentIcon,
  StitchStockIcon,
  StitchFundIcon,
  StitchBondIcon,
  StitchProviderBankIcon,
  StitchProviderWalletIcon,
  StitchProviderPhoneIcon,
  StitchCoffeeIcon,
  StitchFoodIcon,
  StitchRestaurantIcon,
  StitchGroceriesIcon,
  StitchDiningOutIcon,
  StitchSnacksIcon,
  StitchShoppingIcon,
  StitchClothingIcon,
  StitchBeautyIcon,
  StitchGiftIcon,
  StitchCelebrationIcon,
  StitchTravelIcon,
  StitchFlightIcon,
  StitchHotelIcon,
  StitchTransportIcon,
  StitchFuelIcon,
  StitchParkingIcon,
  StitchPublicTransitIcon,
  StitchTaxiIcon,
  StitchVehicleIcon,
  StitchHomeIcon,
  StitchRentIcon,
  StitchMortgageIcon,
  StitchUtilitiesIcon,
  StitchElectricityIcon,
  StitchWaterIcon,
  StitchInternetIcon,
  StitchPhoneIcon,
  StitchHouseholdSuppliesIcon,
  StitchRepairsIcon,
  StitchFurnitureIcon,
  StitchHealthIcon,
  StitchMedicineIcon,
  StitchFitnessIcon,
  StitchEducationIcon,
  StitchBooksIcon,
  StitchChildcareIcon,
  StitchPetsIcon,
  StitchEntertainmentIcon,
  StitchStreamingIcon,
  StitchGamingIcon,
  StitchFamilyIcon,
  StitchCharityIcon,
  StitchInsuranceIcon,
  StitchTaxesIcon,
  StitchFeesIcon,
  StitchSalaryIcon,
  StitchFreelanceIcon,
  StitchBusinessIncomeIcon,
  StitchBonusIcon,
  StitchInvestmentIncomeIcon,
  StitchSubscriptionIcon,
  StitchWeddingIcon,
  StitchFuneralIcon,
  StitchReligiousGivingIcon,
  StitchPersonalCareIcon,
  StitchElectronicsIcon,
  StitchOfficeIcon,
  StitchChildcareSchoolIcon,
  StitchVacationIcon,
  StitchHobbyIcon,
  StitchRefundCategoryIcon,
  StitchBankFeeIcon,
  StitchOtherIcon,
} from "./stitch-icon-artwork";

/** Safe maps for persisted choices; never interpret an icon key as a file path. */
export const ACCOUNT_ICON_BY_KEY: Record<AccountIconKey, IconSvgElement> = {
  [IconKey.ACCOUNT]: StitchAccountIcon,
  [IconKey.BANK]: StitchBankIcon,
  [IconKey.WALLET]: StitchWalletIcon,
  [IconKey.CASH]: StitchCashIcon,
  [IconKey.BANKNOTE]: StitchBanknoteIcon,
  [IconKey.COINS]: StitchCoinsIcon,
  [IconKey.CREDIT_CARD]: StitchCreditCardIcon,
  [IconKey.DEBIT_CARD]: StitchDebitCardIcon,
  [IconKey.SAVINGS]: StitchSavingsIcon,
  [IconKey.SAVINGS_ACCOUNT]: StitchSavingsAccountIcon,
  [IconKey.PIGGY_BANK]: StitchPiggyBankIcon,
  [IconKey.VAULT]: StitchVaultIcon,
  [IconKey.SAFE]: StitchSafeIcon,
  [IconKey.INVESTMENT]: StitchInvestmentIcon,
  [IconKey.STOCK]: StitchStockIcon,
  [IconKey.FUND]: StitchFundIcon,
  [IconKey.BOND]: StitchBondIcon,
  [IconKey.PROVIDER_BANK]: StitchProviderBankIcon,
  [IconKey.PROVIDER_WALLET]: StitchProviderWalletIcon,
  [IconKey.PROVIDER_PHONE]: StitchProviderPhoneIcon,
};

export const CATEGORY_ICON_BY_KEY: Record<CategoryIconKey, IconSvgElement> = {
  [IconKey.COFFEE]: StitchCoffeeIcon,
  [IconKey.FOOD]: StitchFoodIcon,
  [IconKey.RESTAURANT]: StitchRestaurantIcon,
  [IconKey.GROCERIES]: StitchGroceriesIcon,
  [IconKey.DINING_OUT]: StitchDiningOutIcon,
  [IconKey.SNACKS]: StitchSnacksIcon,
  [IconKey.SHOPPING]: StitchShoppingIcon,
  [IconKey.CLOTHING]: StitchClothingIcon,
  [IconKey.BEAUTY]: StitchBeautyIcon,
  [IconKey.GIFT]: StitchGiftIcon,
  [IconKey.CELEBRATION]: StitchCelebrationIcon,
  [IconKey.TRAVEL]: StitchTravelIcon,
  [IconKey.FLIGHT]: StitchFlightIcon,
  [IconKey.HOTEL]: StitchHotelIcon,
  [IconKey.TRANSPORT]: StitchTransportIcon,
  [IconKey.FUEL]: StitchFuelIcon,
  [IconKey.PARKING]: StitchParkingIcon,
  [IconKey.PUBLIC_TRANSIT]: StitchPublicTransitIcon,
  [IconKey.TAXI]: StitchTaxiIcon,
  [IconKey.VEHICLE]: StitchVehicleIcon,
  [IconKey.HOME]: StitchHomeIcon,
  [IconKey.RENT]: StitchRentIcon,
  [IconKey.MORTGAGE]: StitchMortgageIcon,
  [IconKey.UTILITIES]: StitchUtilitiesIcon,
  [IconKey.ELECTRICITY]: StitchElectricityIcon,
  [IconKey.WATER]: StitchWaterIcon,
  [IconKey.INTERNET]: StitchInternetIcon,
  [IconKey.PHONE]: StitchPhoneIcon,
  [IconKey.HOUSEHOLD_SUPPLIES]: StitchHouseholdSuppliesIcon,
  [IconKey.REPAIRS]: StitchRepairsIcon,
  [IconKey.FURNITURE]: StitchFurnitureIcon,
  [IconKey.HEALTH]: StitchHealthIcon,
  [IconKey.MEDICINE]: StitchMedicineIcon,
  [IconKey.FITNESS]: StitchFitnessIcon,
  [IconKey.EDUCATION]: StitchEducationIcon,
  [IconKey.BOOKS]: StitchBooksIcon,
  [IconKey.CHILDCARE]: StitchChildcareIcon,
  [IconKey.PETS]: StitchPetsIcon,
  [IconKey.ENTERTAINMENT]: StitchEntertainmentIcon,
  [IconKey.STREAMING]: StitchStreamingIcon,
  [IconKey.GAMING]: StitchGamingIcon,
  [IconKey.FAMILY]: StitchFamilyIcon,
  [IconKey.CHARITY]: StitchCharityIcon,
  [IconKey.INSURANCE]: StitchInsuranceIcon,
  [IconKey.TAXES]: StitchTaxesIcon,
  [IconKey.FEES]: StitchFeesIcon,
  [IconKey.SALARY]: StitchSalaryIcon,
  [IconKey.FREELANCE]: StitchFreelanceIcon,
  [IconKey.BUSINESS_INCOME]: StitchBusinessIncomeIcon,
  [IconKey.BONUS]: StitchBonusIcon,
  [IconKey.INVESTMENT_INCOME]: StitchInvestmentIncomeIcon,
  [IconKey.SUBSCRIPTION]: StitchSubscriptionIcon,
  [IconKey.WEDDING]: StitchWeddingIcon,
  [IconKey.FUNERAL]: StitchFuneralIcon,
  [IconKey.RELIGIOUS_GIVING]: StitchReligiousGivingIcon,
  [IconKey.PERSONAL_CARE]: StitchPersonalCareIcon,
  [IconKey.ELECTRONICS]: StitchElectronicsIcon,
  [IconKey.OFFICE]: StitchOfficeIcon,
  [IconKey.CHILDCARE_SCHOOL]: StitchChildcareSchoolIcon,
  [IconKey.VACATION]: StitchVacationIcon,
  [IconKey.HOBBY]: StitchHobbyIcon,
  [IconKey.REFUND_CATEGORY]: StitchRefundCategoryIcon,
  [IconKey.BANK_FEE]: StitchBankFeeIcon,
  [IconKey.OTHER]: StitchOtherIcon,
};
